// <auto-generated />
using Lab4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab4.Migrations
{
    [DbContext(typeof(WorkContext))]
    [Migration("20190303091539_AddWorkerHobby")]
    partial class AddWorkerHobby
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab4.Models.Project", b =>
                {
                    b.Property<int>("ProjectID");

                    b.Property<int>("Award");

                    b.Property<string>("Name");

                    b.Property<int>("WorkerID");

                    b.HasKey("ProjectID");

                    b.HasIndex("WorkerID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Lab4.Models.Worker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName");

                    b.Property<string>("Hobby");

                    b.HasKey("ID");

                    b.ToTable("Worker");
                });

            modelBuilder.Entity("Lab4.Models.Project", b =>
                {
                    b.HasOne("Lab4.Models.Worker", "Worker")
                        .WithMany("Projects")
                        .HasForeignKey("WorkerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
